-- CreateTable
CREATE TABLE "Aisle" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "posX" REAL NOT NULL DEFAULT 0,
    "posZ" REAL NOT NULL DEFAULT 0
);

-- CreateTable
CREATE TABLE "Rack" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "aisleId" INTEGER NOT NULL,
    "posX" REAL NOT NULL DEFAULT 0,
    "posZ" REAL NOT NULL DEFAULT 0,
    "width" REAL NOT NULL DEFAULT 1,
    "height" REAL NOT NULL DEFAULT 2.5,
    "depth" REAL NOT NULL DEFAULT 0.8,
    CONSTRAINT "Rack_aisleId_fkey" FOREIGN KEY ("aisleId") REFERENCES "Aisle" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
